const MAIN_NAME = 'Movies.';

export const SEED_MOVIES = `${MAIN_NAME}SEED_MOVIES`;
export const FETCH_MOVIES = `${MAIN_NAME}FETCH_MOVIES`;
export const LOADING_CONTROL_MOVIES = `${MAIN_NAME}LOADING_CONTROL_MOVIES`;
export const RESET_MOVIES = `${MAIN_NAME}RESET_MOVIES`;
