const MAIN_NAME = 'Cart.';

export const ADD_TO_CART = `${MAIN_NAME}ADD_TO_CART`;
export const EDIT_QUANTITY_TO_CART = `${MAIN_NAME}EDIT_QUANTITY_TO_CART`;
export const INCREMENT_QUANTITY_TO_CART = `${MAIN_NAME}INCREMENT_QUANTITY_TO_CART`;
export const DECREMENT_QUANTITY_TO_CART = `${MAIN_NAME}DECREMENT_QUANTITY_TO_CART`;
export const REMOVE_MOVIE_FROM_CART = `${MAIN_NAME}REMOVE_MOVIE_FROM_CART`;
export const RESET_CART = `${MAIN_NAME}RESET_CART`;
